name: Upload Python Package
on:
  release:
    types: [ published ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abatilo/actions-poetry@v2

      - name: Bump version
        run: |
          version=${{ github.event.release.tag_name }}
          poetry version $version
          sed -i "s/__version__ = .*/__version__ = \'${version}\'/g" ./selene/__init__.py

      - name: Commit version
        uses: EndBug/add-and-commit@v9
        with:
          add: '["pyproject.toml", "selene/__init__.py"]'
          branch: 'master'
          message: 'bump version up to ${{ github.event.release.tag_name }}'

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
